#!/usr/bin/env bash
#MISE description="Tag image with additional tag (usage: TAG=stable mise run docker:tag)"
${CONTAINER_CMD:-docker} tag "${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}" "${IMAGE_REGISTRY}/${IMAGE_NAME}:${TAG}"
